### ISSUE TITLE
Création app - Chemin mal construit

### ISSUE THREAD

**Issue by Frata23** [Arquake/Djangler#1]
Apres un `dja new` reussi :

> App created with success !
> Created at : C:\...\...\.../NomApp

Le '/' juste avant le nom de l'app est inversé par rapport aux autres, retirant la possibilité de copié le chemin pour l'utiliser.

**Comment by Arquake** [comment]
Fixed in the latest release :
[Djangler 1.1.0](https://github.com/Arquake/Djangler/releases)
